mutation createPost($createPostId: ID!) {
  createPost(id: $createPostId) {
    ... on Post {
      id
    }
  }
}

mutation CreatePost($data: createPostInput!) {
  createPost(data: $data) {
    ... on Post {
      id
    }

    ... on PostError {
      statusCode
    }
  }
}
