query GetUsers {
  users {
    id
    userName
  }
}

query GET_HI {
  hi
}

query GET_USERS {
  users {
    id
  }
}

query GET_POST {
  post {
    id
  }
}

query getUSer {
  user(id: "903") {
    id
    firstName
  }
}

query getPost {
  post(id: "15") {
    body
    title
    indexRef
    createdAt
    id
  }
}

query getPost($postId: ID!) {
  post(id: $postId) {
    body
    title
    indexRef
    createdAt
    id
  }
}

query getPost {
  postsExample:posts {
    id
    unixTimeStamp
  }
}



