query GetUsers {
  users {
    id
    userName
  }
}

query GET_HI {
  hi
}

query GET_USERS {
  users {
    id
  }
}

query GET_POST {
  post {
    id
  }
}

query getUSer {
  user(id: "903") {
    id
    firstName
  }
}

query getPost {
  post(id: "15") {
    body
    title
    indexRef
    createdAt
    id
  }
}

query getPost($postId: ID!) {
  post(id: $postId) {
    body
    title
    indexRef
    createdAt
    id
  }
}

query getPosts {
  postsExample:posts {
    id
    unixTimeStamp
  }
}

fragment post on Post {
  id
  title
}

query getPost {
  post1:post(id: "860") {
    ...post
  }

  post2:post(id: "783") {
    ...post
  }
}

query getPosts {
  posts(input: {
    _sort: "id",
    _order: "desc",
    _start: 0,
    _limit: 1
  }) {
    id
    title
  }
}

query getPost {
  post(id: "783") {
    ... on Post {
      id
      title
    }

    ... on PostNotFoundError {
      statusCode
    }
  }
}

query getPost {
  post(id: "783") {
    ... on Post {
      id
      title
    }

    ... on PostError {
      statusCode
    }
  }
}

query QueryTrivialResolver($postId: ID!) {
  post(id: $postId) {
    ... on Post {
      id
      title
      user {
        id
        lastName
        firstName
      }
    }

    ... on PostError {
      statusCode
    }
  }
}

query QueryTrivialResolver {
  posts {
    title
    user {
      id
      firstName
    }
  }
}

query UsersWithPosts {
  users {
    id

    posts {
      id
      title
    }
  }
}

query UserWithPosts($userId: ID!) {
  user(id: $userId) {
    id
    posts {
      title
    }
  }
}

query PostWithDataSource($postId: ID!) {
  post(id: $postId) {
    ... on PostError {
      statusCode
    }

    ... on Post {
      title
    }
  }
}

query PostsWithDataSource {
  posts {
    id
    title
  }
}

query Post($postId: ID!) {
  post(id: $postId) {
    ... on Post {
      title,
      user {
        firstName
      }
    }
  }
}
