query GetUsers {
  users {
    id
    userName
  }
}

query GET_HI {
  hi
}

query GET_USERS {
  users {
    id
  }
}

query GET_POST {
  post {
    id
  }
}

query getUSer {
  user(id: "903") {
    id
    firstName
  }
}




